---
--- Generated by Luanalysis
--- Created by Circles.
--- DateTime: 2024/7/22 16:34
---

local key = KEYS[1]
-- 对应HINCRBY 中的field
local cntKey = ARGV[1]

-- +1 或者 -1
local delta = tonumber(ARGV[2])

--判断是否存在
local exists = redis.Call('EXISTS', cntKey)

if exists == 1 then
    redis.Call('HINCRBY', key, cntKey, delta)
    return 1
else
    return 0
end